const prayers={
 morning:{emoji:'🌅',title:'Oração da manhã',text:'Senhor, obrigado por me conceder um novo dia. Coloco diante de Ti meus planos, minha família, meu trabalho e tudo aquilo que está no meu coração. Guia meus passos, dá-me sabedoria e ajuda-me a fazer o bem. Que eu tenha fé para enfrentar cada desafio e gratidão para reconhecer cada bênção. Amém.'},
 night:{emoji:'🌙',title:'Oração da noite',text:'Meu Deus, a noite chegou e eu entrego a Ti tudo o que vivi hoje. Acalma meu coração, perdoa minhas falhas e guarda minha família. Que eu possa descansar em paz, confiando que não estou sozinho. Renova minhas forças para o amanhã e cobre meu lar com Tua paz. Amém.'},
 family:{emoji:'❤️',title:'Oração pela família',text:'Senhor, abençoa minha família. Protege cada pessoa que amo, fortalece nossos laços, traz diálogo, respeito e união para o nosso lar. Nos momentos difíceis, dá-nos paciência e fé. Que nunca falte amor, esperança e a Tua presença entre nós. Amém.'},
 health:{emoji:'🕊️',title:'Oração por saúde e cuidado',text:'Deus de misericórdia, coloco diante de Ti minhas preocupações e as de quem amo. Concede força, conforto e esperança. Abençoa todos que cuidam de nós e dá sabedoria para cada decisão. Que a paz alcance o coração e que a fé permaneça firme em todos os momentos. Amém.'},
 gratitude:{emoji:'✨',title:'Oração de agradecimento',text:'Senhor, obrigado pela vida, pelo alimento, pela família, pelas oportunidades e até pelas lições dos dias difíceis. Muitas bênçãos passam despercebidas, mas hoje escolho agradecer. Ensina-me a viver com um coração grato e a reconhecer Tua bondade em cada detalhe. Amém.'},
 anxiety:{emoji:'🤍',title:'Oração para acalmar o coração',text:'Pai, quando meus pensamentos estiverem acelerados, ajuda-me a respirar e lembrar que posso entregar minhas preocupações a Ti. Dá-me serenidade para o que não posso controlar e coragem para o que posso enfrentar. Guarda meu coração e renova minha esperança. Amém.'}
};
const dialog=document.getElementById('prayerDialog'),title=document.getElementById('dialogTitle'),text=document.getElementById('dialogText'),emoji=document.getElementById('dialogEmoji');let current='';
function openPrayer(key){const p=prayers[key];if(!p)return;current=key;emoji.textContent=p.emoji;title.textContent=p.title;text.textContent=p.text;document.getElementById('favBtn').textContent=isFav(key)?'♥ Favoritado':'♡ Favoritar';dialog.showModal()}
function isFav(k){return JSON.parse(localStorage.getItem('ora-favs')||'[]').includes(k)}
function toggleFav(k){let a=JSON.parse(localStorage.getItem('ora-favs')||'[]');a=a.includes(k)?a.filter(x=>x!==k):[...a,k];localStorage.setItem('ora-favs',JSON.stringify(a));renderFavs()}
function renderFavs(){const box=document.getElementById('favorites'),a=JSON.parse(localStorage.getItem('ora-favs')||'[]');if(!a.length){box.className='empty';box.textContent='Toque no coração de uma oração para salvá-la aqui.';return}box.className='grid';box.innerHTML=a.map(k=>`<button class="prayer-card small" data-open="${k}"><span>${prayers[k].emoji}</span><h3>${prayers[k].title}</h3><p>Seu favorito</p></button>`).join('');box.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openPrayer(b.dataset.open))}
function speak(content){if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(content);u.lang='pt-BR';u.rate=.9;u.pitch=.9;window.speechSynthesis.speak(u)}
document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>openPrayer(b.dataset.open)));document.querySelectorAll('[data-scroll]').forEach(b=>b.addEventListener('click',()=>document.getElementById(b.dataset.scroll).scrollIntoView({behavior:'smooth'})));
document.getElementById('closeDialog').onclick=()=>dialog.close();document.getElementById('favBtn').onclick=()=>{toggleFav(current);document.getElementById('favBtn').textContent=isFav(current)?'♥ Favoritado':'♡ Favoritar'};document.getElementById('speakBtn').onclick=()=>speak(text.textContent);document.querySelector('.read-btn').onclick=()=>speak(document.querySelector('.featured p').textContent);
document.getElementById('themeBtn').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('ora-theme',document.body.classList.contains('light')?'light':'dark')};if(localStorage.getItem('ora-theme')==='light')document.body.classList.add('light');
document.querySelector('[data-nav="favorites"]').onclick=()=>document.querySelector('.favorites-section').scrollIntoView({behavior:'smooth'});document.querySelector('[data-nav="home"]').onclick=()=>window.scrollTo({top:0,behavior:'smooth'});
const d=new Date();document.getElementById('dateLabel').textContent=d.toLocaleDateString('pt-BR',{day:'2-digit',month:'long',year:'numeric'});renderFavs();
